version: "3.1"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: rp_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  backend:
    build:
      context: backend
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
